<?php $__env->startSection('title', 'Novo produto'); ?>
<?php $__env->startSection('heading', 'Novo produto'); ?>
<?php $__env->startSection('content'); ?>
<div class="mx-auto max-w-4xl"><div class="mb-6"><a href="<?php echo e(route('products.index')); ?>" class="text-sm font-medium text-emerald-700 hover:text-emerald-900">← Voltar para produtos</a><h2 class="mt-3 text-2xl font-bold">Cadastrar produto e primeira variação</h2><p class="mt-1 text-sm text-slate-500">Nesta versão, cada cadastro cria um modelo e sua primeira combinação de tamanho e cor. Mais variações poderão ser adicionadas em etapa posterior.</p></div>
<form method="POST" action="<?php echo e(route('products.store')); ?>" class="space-y-6"><?php echo csrf_field(); ?>
<section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h3 class="font-semibold">Informações do produto</h3><div class="mt-5 grid gap-5 sm:grid-cols-2"><label class="block sm:col-span-2"><span class="text-sm font-medium">Nome do produto *</span><input name="name" required maxlength="160" value="<?php echo e(old('name')); ?>" class="mt-1.5 w-full rounded-xl border border-slate-300 px-3 py-2.5 outline-none focus:border-emerald-600 focus:ring-2 focus:ring-emerald-100"></label><label class="block"><span class="text-sm font-medium">Categoria</span><input name="category" value="<?php echo e(old('category')); ?>" placeholder="Ex.: Camisetas" class="mt-1.5 w-full rounded-xl border border-slate-300 px-3 py-2.5 outline-none focus:border-emerald-600"></label><label class="block"><span class="text-sm font-medium">Marca</span><input name="brand" value="<?php echo e(old('brand')); ?>" class="mt-1.5 w-full rounded-xl border border-slate-300 px-3 py-2.5 outline-none focus:border-emerald-600"></label><label class="block sm:col-span-2"><span class="text-sm font-medium">Descrição</span><textarea name="description" rows="3" class="mt-1.5 w-full rounded-xl border border-slate-300 px-3 py-2.5 outline-none focus:border-emerald-600"><?php echo e(old('description')); ?></textarea></label></div></section>
<section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h3 class="font-semibold">Primeira variação</h3><p class="mt-1 text-sm text-slate-500">SKU deve ser único. O código de barras é opcional.</p><div class="mt-5 grid gap-5 sm:grid-cols-2"><label class="block"><span class="text-sm font-medium">Tamanho *</span><input name="size" required value="<?php echo e(old('size')); ?>" placeholder="P, M, G, 38..." class="mt-1.5 w-full rounded-xl border border-slate-300 px-3 py-2.5 outline-none focus:border-emerald-600"></label><label class="block"><span class="text-sm font-medium">Cor *</span><input name="color" required value="<?php echo e(old('color')); ?>" placeholder="Preto" class="mt-1.5 w-full rounded-xl border border-slate-300 px-3 py-2.5 outline-none focus:border-emerald-600"></label><label class="block"><span class="text-sm font-medium">SKU *</span><input name="sku" required value="<?php echo e(old('sku')); ?>" class="mt-1.5 w-full rounded-xl border border-slate-300 px-3 py-2.5 outline-none focus:border-emerald-600"></label><label class="block"><span class="text-sm font-medium">Código de barras</span><input name="barcode" value="<?php echo e(old('barcode')); ?>" class="mt-1.5 w-full rounded-xl border border-slate-300 px-3 py-2.5 outline-none focus:border-emerald-600"></label><label class="block"><span class="text-sm font-medium">Preço de custo (R$) *</span><input type="number" name="cost_price" min="0" step="0.01" required value="<?php echo e(old('cost_price', '0.00')); ?>" class="mt-1.5 w-full rounded-xl border border-slate-300 px-3 py-2.5 outline-none focus:border-emerald-600"></label><label class="block"><span class="text-sm font-medium">Preço de venda (R$) *</span><input type="number" name="sale_price" min="0" step="0.01" required value="<?php echo e(old('sale_price', '0.00')); ?>" class="mt-1.5 w-full rounded-xl border border-slate-300 px-3 py-2.5 outline-none focus:border-emerald-600"></label><label class="block"><span class="text-sm font-medium">Estoque inicial (unidades) *</span><input type="number" name="initial_stock" min="0" step="1" required value="<?php echo e(old('initial_stock', '0')); ?>" class="mt-1.5 w-full rounded-xl border border-slate-300 px-3 py-2.5 outline-none focus:border-emerald-600"></label></div></section>
<div class="flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><a href="<?php echo e(route('products.index')); ?>" class="rounded-xl border border-slate-300 bg-white px-5 py-3 text-center text-sm font-semibold text-slate-700 hover:bg-slate-50">Cancelar</a><button class="rounded-xl bg-emerald-700 px-5 py-3 text-sm font-semibold text-white hover:bg-emerald-800">Salvar produto</button></div>
</form></div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.app', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\Users\kleyton.santos\Downloads\loja-roupas-inicial\loja-roupas-inicial\loja-roupas-app\resources\views/products/create.blade.php ENDPATH**/ ?>